openapi: 3.0.1
info:
  title: Findchips API
  description: API for searching chips, prices, and details
  version: 1.0.0
servers:
  - url: https://www.findchips.com
paths:
  /search/:
    post:
      summary: find chip details 
      description: >
        Search for a manufacturer part number to find price, availablity and datasheets from top distributors worldwide.
        Filter your results by manufacturer, in-stock items only, exact part matches and quantity.

        Example input code:
        ```sn75468d
        ```

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: >
                    Search for a manufacturer part number to find price, availablity and datasheets from top distributors worldwide.
                    Filter your results by manufacturer, in-stock items only, exact part matches and quantity.
                    Example:
                    ```sn75468d
                    ```
              required:
                - code
      responses:
        '200':
          description: URL of findchips search
          content:
            text/plain:
              schema:
                type: string
                example: "https://www.findchips.com/search/<chip>"
        '400':
          description: Error processing the request
          content:
            text/plain:
              schema:
                type: string
                example: "Error: <error_message>"
components:
  securitySchemes:
    function_key:
      type: apiKey
      name: x-functions-key
      in: header
security:
  - function_key: []
